using UnityEngine;

namespace FractalShader
{
	/// <summary>
	/// Main application class for rendering 3D Mandelbulb fractals.
	/// Inherits from the base App class to communicate with the Compute Shader via URP.
	/// </summary>
	public class Mandelbulb : App
	{
		// Singleton instance for global access
		public static Mandelbulb Instance { get; private set; }

		[Header("--- SHAPE & MATHEMATICS ---")]
		[Tooltip("The exponent used in the Mandelbulb formula (z^power + c). Higher values create more lobes.")]
		[Range(1f, 20f)] public float power = 8f;

		[Tooltip("The number of escape-time iterations (Higher = more detail, lower FPS).")]
		[Range(1, 100)] public int iterations = 30;

		[Tooltip("Blends between the standard Mandelbulb (0) and the Julia set (1).")]
		[Range(0f, 1f)] public float julia;

		[Tooltip("The constant 'C' vector used when Julia mode is enabled.")]
		public Vector3 c = Vector3.zero;

		[Tooltip("Toggle between standard and alternative spherical coordinate formulas.")]
		public bool alt;

		[Header("--- COLORS & LIGHTS ---")]
		[Tooltip("The base color of the fractal surface.")]
		public Color fractalColor = new Color(0.8f, 0.2f, 0.2f, 1f);

		[Tooltip("Background color used to clear ghosting artifacts and represent the void.")]
		public Color backgroundColor = Color.black;

		[Tooltip("Blends between the algorithmic orbit trap color and the solid Fractal Color.")]
		[Range(0f, 1f)] public float mix = 0.5f;

		[Tooltip("Multiplier for the glow/light emission intensity.")]
		[Range(0.1f, 10f)] public float emissionStrength = 1.5f;

		[Header("--- FOG & DISTANCE ---")]
		[Tooltip("Controls the density of the depth-based fog.")]
		[Range(10f, 200f)] public float fogDensity = 50f;

		[Tooltip("Maximum raymarching distance. Rays exceeding this will render as background.")]
		[Range(10f, 500f)] public float maxDistance = 100f;

		private void Start()
		{
			// Standard Singleton pattern setup with safety check
			if (Instance != null && Instance != this)
			{
				Destroy(this);
				return;
			}
			Instance = this;

			// Force the camera into Orbit mode for the Mandelbulb view
			cameraType = CameraType.Orbit;
		}

		/// <summary>
		/// The main drawing function called by the base App class.
		/// </summary>
		/// <param name="targetTexture">The texture generated by the Compute Shader.</param>
		protected override void Render(RenderTexture targetTexture)
		{
			// The compute shader dispatch is handled by the MandelbulbFeature (URP Pass).
			// This remains empty intentionally as the ScriptableRendererFeature executes the command buffers.
		}

		#region UI Option Properties

		// Bridge properties designed to connect with the OptionsManager and UI Controllers
		public float O_Power { get => power; set => power = value; }
		public float O_Iterations { get => iterations; set => iterations = Mathf.RoundToInt(value); }
		public float O_Julia { get => julia; set => julia = value; }
		public Vector3 O_C { get => c; set => c = value; }
		public float O_Mix { get => mix; set => mix = value; }
		public bool O_Alt { get => alt; set => alt = value; }

		#endregion
	}
}