using UnityEngine;

namespace FractalShader
{
	/// <summary>
	/// Application class for rendering a Menger Sponge fractal with a cutting plane.
	/// Inherits from the base App class to communicate with the Compute Shader via URP.
	/// </summary>
	public class MengerSponge : App
	{
		// Singleton instance for global access
		public static MengerSponge Instance { get; private set; }

		// Core Fractal Fields
		// Kept private to avoid Inspector clutter as they are managed via the UI system.
		private int iterations;
		private float size = 1f;
		private float edge = 1f;
		private float cut;
		private bool cantor;

		private void Start()
		{
			// Standard Singleton pattern setup with safety check
			if (Instance != null && Instance != this)
			{
				Destroy(this);
				return;
			}
			Instance = this;

			// Initialize the camera to Orbit mode for 360-degree fractal viewing
			cameraType = CameraType.Orbit;
		}

		/// <summary>
		/// The main drawing function called by the base App class.
		/// </summary>
		/// <param name="targetTexture">The texture generated by the Compute Shader.</param>
		protected override void Render(RenderTexture targetTexture)
		{
			// Note: In the URP workflow, actual rendering is handled by the MengerSpongeFeature (ScriptableRendererFeature).
		}

		#region UI Bridge Properties

		/// <summary>
		/// Properties used to bridge the internal state with the custom UI system.
		/// These methods ensure values are correctly clamped and rounded before being sent to the GPU.
		/// </summary>

		public float O_Iterations
		{
			get => iterations;
			set => iterations = Mathf.RoundToInt(value);
		}

		public float O_Size
		{
			get => size;
			set => size = value;
		}

		public float O_Edge
		{
			get => edge;
			set => edge = value;
		}

		public float O_Cut
		{
			get => cut;
			set => cut = value;
		}

		public bool O_Cantor
		{
			get => cantor;
			set => cantor = value;
		}

		#endregion
	}
}