using UnityEngine;

namespace FractalShader
{
	/// <summary>
	/// Main application class that handles the Mandelbox fractal rendering.
	/// Inherits from the base App class to communicate with the Compute Shader.
	/// </summary>
	public class Mandelbox : App
	{
		// Singleton instance for global access
		public static Mandelbox Instance { get; private set; }

		[Header("--- BOX SHAPE ---")]
		[Tooltip("The fractal scale factor. Determines the folding intensity.")]
		[Range(0.5f, 5f)] public float scale = 2f;

		[Tooltip("Detail level of the fractal (Higher = more detail, lower FPS).")]
		[Range(1, 50)] public int iterations = 20;

		[Header("--- LIVE PERFORMANCE ---")]
		[Tooltip("Stops fractal recursion once its next detail is below a pixel at the current ray distance.")]
		public bool pixelFootprintCulling = true;

		[Tooltip("Minimum recursion retained by pixel-footprint culling, preserving the main Mandelbox form.")]
		[Range(1, 24)] public int minimumVisibleIterations = 10;

		[Tooltip("Alternates only the finest detail between pixel groups each frame. This is deliberately lively and is intended for VJ use.")]
		public bool vjInterleavedDetail = true;

		[Tooltip("Iterations at or below this are rendered for every pixel; only finer detail is interleaved.")]
		[Range(1, 32)] public int stableIterations = 16;

		[Tooltip("Toggle Julia set mode. Uses the 'C' vector instead of the spatial position.")]
		public bool julia;

		[Tooltip("The constant vector used when Julia mode is enabled.")]
		public Vector3 c = Vector3.zero;

		[Header("--- COLORS & LIGHTS ---")]
		[Tooltip("The base color of the Mandelbox.")]
		public Color boxColor = new Color(0.04f, 0.59f, 0.78f, 1f);

		[Tooltip("Background color for clearing ghosting artifacts and representing the void.")]
		public Color backgroundColor = Color.black;

		[Tooltip("Blends between the algorithmic orbit trap color and the solid Box Color.")]
		[Range(0f, 1f)] public float mix = 0.5f;

		[Tooltip("Intensity of the glow/emission effect.")]
		[Range(0.1f, 10f)] public float emissionStrength = 2f;

		[Header("--- FOG & DISTANCE ---")]
		[Tooltip("Density of the depth-based fog.")]
		[Range(10f, 200f)] public float fogDensity = 80f;

		[Tooltip("Maximum raymarching distance. Rays traveling further than this will render as background.")]
		[Range(10f, 500f)] public float maxDistance = 100f;

		private void Start()
		{
			// Standard Singleton pattern setup with safety check
			if (Instance != null && Instance != this)
			{
				Destroy(this);
				return;
			}
			Instance = this;

			// Force the camera into Orbit mode for the Mandelbox
			cameraType = CameraType.Orbit;

			// Configure orbital camera constraints
			if (controlsHelper != null)
			{
				controlsHelper.sensitivity = 4f;
				controlsHelper.minRadius = 0.5f;
				controlsHelper.maxRadius = 20f;
			}
		}

		/// <summary>
		/// The main drawing function called by the base App class.
		/// </summary>
		/// <param name="targetTexture">The texture generated by the Compute Shader.</param>
		protected override void Render(RenderTexture targetTexture)
		{
			// NOTE: The Compute Shader dispatch is handled by the MandelboxFeature (URP Pass).
			// This remains empty intentionally as the ScriptableRendererFeature executes the command buffers.
		}

		#region UI Option Properties

		// Properties strictly designed to bridge with the OptionsManager and UI Controllers
		public float O_Scale { get => scale; set => scale = value; }
		public float O_Iterations { get => iterations; set => iterations = Mathf.RoundToInt(value); }
		public bool O_Julia { get => julia; set => julia = value; }
		public Vector3 O_C { get => c; set => c = value; }
		public float O_Mix { get => mix; set => mix = value; }

		/// <summary>
		/// Hidden converter property. 
		/// Solves the mismatch between the UI system (which sends a Vector3 from 0-255) 
		/// and the Inspector (which uses Unity's Color format from 0.0 to 1.0).
		/// </summary>
		public Vector3 O_Color
		{
			get => new Vector3(boxColor.r * 255f, boxColor.g * 255f, boxColor.b * 255f);
			set => boxColor = new Color(value.x / 255f, value.y / 255f, value.z / 255f, 1f);
		}

		#endregion
	}
}
