using UnityEngine;

namespace FractalShader
{
	/// <summary>
	/// Main application class that handles the Menger Sponge (FRAX) rendering.
	/// Inherits from the base App class to communicate with the Compute Shader.
	/// </summary>
	public class FRAX : App
	{
		// Singleton instance for global access
		public static FRAX Instance { get; private set; }

		[Header("--- ANIMATED VARIABLES (AC) ---")]
		[Tooltip("Dynamically animated edge thickness parameter.")]
		public float currentEdge = 1.8f;

		[Tooltip("Dynamically animated space bending vector.")]
		public Vector3 currentCurveSpace = Vector3.zero;

		[Tooltip("Multiplier for the space bending effect.")]
		public float curve = 1f;

		[Header("--- FRACTAL SHAPE ---")]
		[Tooltip("The overall structural size of the fractal.")]
		[Range(1f, 20f)] public float size = 5f;

		[Tooltip("Detail level of the fractal nesting (Higher = more detail, lower FPS).")]
		[Range(1, 15)] public int iterations = 5;

		[Header("--- COLORS & LIGHTS ---")]
		[Tooltip("Color of the neon glows and ambient occlusion accents.")]
		public Color accentColor = new Color(0.55f, 0.65f, 1f, 1f);

		[Tooltip("Background color representing the void of space.")]
		public Color backgroundColor = new Color(0.06f, 0.06f, 0.12f, 1f);

		[Tooltip("Intensity multiplier for the glow brightness.")]
		[Range(0.1f, 5f)] public float colorIntensity = 1f;

		// Internal Animation Controller IDs
		private int edgeID;
		private int curveSpaceXID;
		private int curveSpaceYID;
		private int curveSpaceZID;

		private void Start()
		{
			// Standard Singleton pattern setup with safety check
			if (Instance != null && Instance != this)
			{
				Destroy(this);
				return;
			}
			Instance = this;

			// Ensure the camera renders a depth texture (useful if you ever integrate post-processing)
			if (cam != null)
			{
				cam.depthTextureMode = DepthTextureMode.Depth;
			}

			// Lock the camera radius to keep the perspective consistent
			if (controlsHelper != null)
			{
				controlsHelper.minRadius = 2f;
				controlsHelper.maxRadius = 2f;
			}

			// Register variables to the Animation Controller for continuous modification
			if (animationController != null)
			{
				edgeID = animationController.Register(currentEdge, 0.127f, 1.8f, 2.45f, true);
				curveSpaceXID = animationController.Register(currentCurveSpace.x, 0.095f, -1f, 1f, true);
				curveSpaceYID = animationController.Register(currentCurveSpace.y, 0.064f, -1f, 1f, true);
				curveSpaceZID = animationController.Register(currentCurveSpace.z, 0.032f, -1f, 1f, true);
			}
		}

		protected override void Update()
		{
			// Call the base class Update (handles FPS counter, etc.)
			base.Update();

			// Continuously fetch updated animation data
			if (animationController != null)
			{
				animationController.Get(edgeID, ref currentEdge);
				currentCurveSpace = new Vector3(
					animationController.Get(curveSpaceXID),
					animationController.Get(curveSpaceYID),
					animationController.Get(curveSpaceZID)
				);
			}
		}

		/// <summary>
		/// The main drawing function called by the base App class.
		/// </summary>
		/// <param name="targetTexture">The texture generated by the Compute Shader.</param>
		protected override void Render(RenderTexture targetTexture)
		{
			// NOTE: The Compute Shader dispatch is handled by the FRAXFeature (URP Pass).
			// This remains empty intentionally as the ScriptableRendererFeature executes the command buffers.
		}

		#region UI Option Properties

		// Property strictly designed to bridge with the OptionsManager and UI Controllers
		public float O_Curve
		{
			get => curve;
			set => curve = value;
		}

		#endregion
	}
}